version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel

  mariadb:
    image: mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
    env_file:
      - ./config.env
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: php-dockerfile
    container_name: php
    working_dir: /var/www
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www
      - ./php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - laravel
